name: ci

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12.3, 3.11.4, 3.10.12]

    steps:
      - name: Baixando o código
        uses: actions/checkout@v4

      - name: Instalando o python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: fazendo um pwd
        run: echo $(pwd)